[package]
name = "mone"
version = "0.1.0"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.0"
pcap = { version = "0.7", features = ["tokio"] }
tokio-core = "0.1.0"
